// Z80 Opcode Reference Data — extracted from index.html

export const z80Opcodes = [
    // Load 8-bit
    { m: 'LD A,A', o: '7F', b: 1, c: '4', f: '------', d: 'Load A from A', g: 'load' },
    { m: 'LD A,B', o: '78', b: 1, c: '4', f: '------', d: 'Load A from B', g: 'load' },
    { m: 'LD A,C', o: '79', b: 1, c: '4', f: '------', d: 'Load A from C', g: 'load' },
    { m: 'LD A,D', o: '7A', b: 1, c: '4', f: '------', d: 'Load A from D', g: 'load' },
    { m: 'LD A,E', o: '7B', b: 1, c: '4', f: '------', d: 'Load A from E', g: 'load' },
    { m: 'LD A,H', o: '7C', b: 1, c: '4', f: '------', d: 'Load A from H', g: 'load' },
    { m: 'LD A,L', o: '7D', b: 1, c: '4', f: '------', d: 'Load A from L', g: 'load' },
    { m: 'LD B,A', o: '47', b: 1, c: '4', f: '------', d: 'Load B from A', g: 'load' },
    { m: 'LD B,B', o: '40', b: 1, c: '4', f: '------', d: 'Load B from B', g: 'load' },
    { m: 'LD B,C', o: '41', b: 1, c: '4', f: '------', d: 'Load B from C', g: 'load' },
    { m: 'LD B,D', o: '42', b: 1, c: '4', f: '------', d: 'Load B from D', g: 'load' },
    { m: 'LD B,E', o: '43', b: 1, c: '4', f: '------', d: 'Load B from E', g: 'load' },
    { m: 'LD B,H', o: '44', b: 1, c: '4', f: '------', d: 'Load B from H', g: 'load' },
    { m: 'LD B,L', o: '45', b: 1, c: '4', f: '------', d: 'Load B from L', g: 'load' },
    { m: 'LD C,A', o: '4F', b: 1, c: '4', f: '------', d: 'Load C from A', g: 'load' },
    { m: 'LD C,B', o: '48', b: 1, c: '4', f: '------', d: 'Load C from B', g: 'load' },
    { m: 'LD C,C', o: '49', b: 1, c: '4', f: '------', d: 'Load C from C', g: 'load' },
    { m: 'LD C,D', o: '4A', b: 1, c: '4', f: '------', d: 'Load C from D', g: 'load' },
    { m: 'LD C,E', o: '4B', b: 1, c: '4', f: '------', d: 'Load C from E', g: 'load' },
    { m: 'LD C,H', o: '4C', b: 1, c: '4', f: '------', d: 'Load C from H', g: 'load' },
    { m: 'LD C,L', o: '4D', b: 1, c: '4', f: '------', d: 'Load C from L', g: 'load' },
    { m: 'LD D,A', o: '57', b: 1, c: '4', f: '------', d: 'Load D from A', g: 'load' },
    { m: 'LD D,B', o: '50', b: 1, c: '4', f: '------', d: 'Load D from B', g: 'load' },
    { m: 'LD D,C', o: '51', b: 1, c: '4', f: '------', d: 'Load D from C', g: 'load' },
    { m: 'LD D,D', o: '52', b: 1, c: '4', f: '------', d: 'Load D from D', g: 'load' },
    { m: 'LD D,E', o: '53', b: 1, c: '4', f: '------', d: 'Load D from E', g: 'load' },
    { m: 'LD D,H', o: '54', b: 1, c: '4', f: '------', d: 'Load D from H', g: 'load' },
    { m: 'LD D,L', o: '55', b: 1, c: '4', f: '------', d: 'Load D from L', g: 'load' },
    { m: 'LD E,A', o: '5F', b: 1, c: '4', f: '------', d: 'Load E from A', g: 'load' },
    { m: 'LD E,B', o: '58', b: 1, c: '4', f: '------', d: 'Load E from B', g: 'load' },
    { m: 'LD E,C', o: '59', b: 1, c: '4', f: '------', d: 'Load E from C', g: 'load' },
    { m: 'LD E,D', o: '5A', b: 1, c: '4', f: '------', d: 'Load E from D', g: 'load' },
    { m: 'LD E,E', o: '5B', b: 1, c: '4', f: '------', d: 'Load E from E', g: 'load' },
    { m: 'LD E,H', o: '5C', b: 1, c: '4', f: '------', d: 'Load E from H', g: 'load' },
    { m: 'LD E,L', o: '5D', b: 1, c: '4', f: '------', d: 'Load E from L', g: 'load' },
    { m: 'LD H,A', o: '67', b: 1, c: '4', f: '------', d: 'Load H from A', g: 'load' },
    { m: 'LD H,B', o: '60', b: 1, c: '4', f: '------', d: 'Load H from B', g: 'load' },
    { m: 'LD H,C', o: '61', b: 1, c: '4', f: '------', d: 'Load H from C', g: 'load' },
    { m: 'LD H,D', o: '62', b: 1, c: '4', f: '------', d: 'Load H from D', g: 'load' },
    { m: 'LD H,E', o: '63', b: 1, c: '4', f: '------', d: 'Load H from E', g: 'load' },
    { m: 'LD H,H', o: '64', b: 1, c: '4', f: '------', d: 'Load H from H', g: 'load' },
    { m: 'LD H,L', o: '65', b: 1, c: '4', f: '------', d: 'Load H from L', g: 'load' },
    { m: 'LD L,A', o: '6F', b: 1, c: '4', f: '------', d: 'Load L from A', g: 'load' },
    { m: 'LD L,B', o: '68', b: 1, c: '4', f: '------', d: 'Load L from B', g: 'load' },
    { m: 'LD L,C', o: '69', b: 1, c: '4', f: '------', d: 'Load L from C', g: 'load' },
    { m: 'LD L,D', o: '6A', b: 1, c: '4', f: '------', d: 'Load L from D', g: 'load' },
    { m: 'LD L,E', o: '6B', b: 1, c: '4', f: '------', d: 'Load L from E', g: 'load' },
    { m: 'LD L,H', o: '6C', b: 1, c: '4', f: '------', d: 'Load L from H', g: 'load' },
    { m: 'LD L,L', o: '6D', b: 1, c: '4', f: '------', d: 'Load L from L', g: 'load' },
    { m: 'LD A,n', o: '3E nn', b: 2, c: '7', f: '------', d: 'Load A with immediate', g: 'load' },
    { m: 'LD B,n', o: '06 nn', b: 2, c: '7', f: '------', d: 'Load B with immediate', g: 'load' },
    { m: 'LD C,n', o: '0E nn', b: 2, c: '7', f: '------', d: 'Load C with immediate', g: 'load' },
    { m: 'LD D,n', o: '16 nn', b: 2, c: '7', f: '------', d: 'Load D with immediate', g: 'load' },
    { m: 'LD E,n', o: '1E nn', b: 2, c: '7', f: '------', d: 'Load E with immediate', g: 'load' },
    { m: 'LD H,n', o: '26 nn', b: 2, c: '7', f: '------', d: 'Load H with immediate', g: 'load' },
    { m: 'LD L,n', o: '2E nn', b: 2, c: '7', f: '------', d: 'Load L with immediate', g: 'load' },
    { m: 'LD A,(HL)', o: '7E', b: 1, c: '7', f: '------', d: 'Load A from (HL)', g: 'load' },
    { m: 'LD B,(HL)', o: '46', b: 1, c: '7', f: '------', d: 'Load B from (HL)', g: 'load' },
    { m: 'LD C,(HL)', o: '4E', b: 1, c: '7', f: '------', d: 'Load C from (HL)', g: 'load' },
    { m: 'LD D,(HL)', o: '56', b: 1, c: '7', f: '------', d: 'Load D from (HL)', g: 'load' },
    { m: 'LD E,(HL)', o: '5E', b: 1, c: '7', f: '------', d: 'Load E from (HL)', g: 'load' },
    { m: 'LD H,(HL)', o: '66', b: 1, c: '7', f: '------', d: 'Load H from (HL)', g: 'load' },
    { m: 'LD L,(HL)', o: '6E', b: 1, c: '7', f: '------', d: 'Load L from (HL)', g: 'load' },
    { m: 'LD A,(IX+d)', o: 'DD 7E dd', b: 3, c: '19', f: '------', d: 'Load A from (IX+d)', g: 'load' },
    { m: 'LD B,(IX+d)', o: 'DD 46 dd', b: 3, c: '19', f: '------', d: 'Load B from (IX+d)', g: 'load' },
    { m: 'LD C,(IX+d)', o: 'DD 4E dd', b: 3, c: '19', f: '------', d: 'Load C from (IX+d)', g: 'load' },
    { m: 'LD D,(IX+d)', o: 'DD 56 dd', b: 3, c: '19', f: '------', d: 'Load D from (IX+d)', g: 'load' },
    { m: 'LD E,(IX+d)', o: 'DD 5E dd', b: 3, c: '19', f: '------', d: 'Load E from (IX+d)', g: 'load' },
    { m: 'LD H,(IX+d)', o: 'DD 66 dd', b: 3, c: '19', f: '------', d: 'Load H from (IX+d)', g: 'load' },
    { m: 'LD L,(IX+d)', o: 'DD 6E dd', b: 3, c: '19', f: '------', d: 'Load L from (IX+d)', g: 'load' },
    { m: 'LD A,(IY+d)', o: 'FD 7E dd', b: 3, c: '19', f: '------', d: 'Load A from (IY+d)', g: 'load' },
    { m: 'LD B,(IY+d)', o: 'FD 46 dd', b: 3, c: '19', f: '------', d: 'Load B from (IY+d)', g: 'load' },
    { m: 'LD C,(IY+d)', o: 'FD 4E dd', b: 3, c: '19', f: '------', d: 'Load C from (IY+d)', g: 'load' },
    { m: 'LD D,(IY+d)', o: 'FD 56 dd', b: 3, c: '19', f: '------', d: 'Load D from (IY+d)', g: 'load' },
    { m: 'LD E,(IY+d)', o: 'FD 5E dd', b: 3, c: '19', f: '------', d: 'Load E from (IY+d)', g: 'load' },
    { m: 'LD H,(IY+d)', o: 'FD 66 dd', b: 3, c: '19', f: '------', d: 'Load H from (IY+d)', g: 'load' },
    { m: 'LD L,(IY+d)', o: 'FD 6E dd', b: 3, c: '19', f: '------', d: 'Load L from (IY+d)', g: 'load' },
    { m: 'LD (HL),A', o: '77', b: 1, c: '7', f: '------', d: 'Load (HL) from A', g: 'load' },
    { m: 'LD (HL),B', o: '70', b: 1, c: '7', f: '------', d: 'Load (HL) from B', g: 'load' },
    { m: 'LD (HL),C', o: '71', b: 1, c: '7', f: '------', d: 'Load (HL) from C', g: 'load' },
    { m: 'LD (HL),D', o: '72', b: 1, c: '7', f: '------', d: 'Load (HL) from D', g: 'load' },
    { m: 'LD (HL),E', o: '73', b: 1, c: '7', f: '------', d: 'Load (HL) from E', g: 'load' },
    { m: 'LD (HL),H', o: '74', b: 1, c: '7', f: '------', d: 'Load (HL) from H', g: 'load' },
    { m: 'LD (HL),L', o: '75', b: 1, c: '7', f: '------', d: 'Load (HL) from L', g: 'load' },
    { m: 'LD (IX+d),A', o: 'DD 77 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from A', g: 'load' },
    { m: 'LD (IX+d),B', o: 'DD 70 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from B', g: 'load' },
    { m: 'LD (IX+d),C', o: 'DD 71 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from C', g: 'load' },
    { m: 'LD (IX+d),D', o: 'DD 72 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from D', g: 'load' },
    { m: 'LD (IX+d),E', o: 'DD 73 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from E', g: 'load' },
    { m: 'LD (IX+d),H', o: 'DD 74 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from H', g: 'load' },
    { m: 'LD (IX+d),L', o: 'DD 75 dd', b: 3, c: '19', f: '------', d: 'Load (IX+d) from L', g: 'load' },
    { m: 'LD (IY+d),A', o: 'FD 77 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from A', g: 'load' },
    { m: 'LD (IY+d),B', o: 'FD 70 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from B', g: 'load' },
    { m: 'LD (IY+d),C', o: 'FD 71 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from C', g: 'load' },
    { m: 'LD (IY+d),D', o: 'FD 72 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from D', g: 'load' },
    { m: 'LD (IY+d),E', o: 'FD 73 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from E', g: 'load' },
    { m: 'LD (IY+d),H', o: 'FD 74 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from H', g: 'load' },
    { m: 'LD (IY+d),L', o: 'FD 75 dd', b: 3, c: '19', f: '------', d: 'Load (IY+d) from L', g: 'load' },
    { m: 'LD (HL),n', o: '36 nn', b: 2, c: '10', f: '------', d: 'Load (HL) with immediate', g: 'load' },
    { m: 'LD (IX+d),n', o: 'DD 36 dd nn', b: 4, c: '19', f: '------', d: 'Load (IX+d) with immediate', g: 'load' },
    { m: 'LD (IY+d),n', o: 'FD 36 dd nn', b: 4, c: '19', f: '------', d: 'Load (IY+d) with immediate', g: 'load' },
    { m: 'LD A,(BC)', o: '0A', b: 1, c: '7', f: '------', d: 'Load A from (BC)', g: 'load' },
    { m: 'LD A,(DE)', o: '1A', b: 1, c: '7', f: '------', d: 'Load A from (DE)', g: 'load' },
    { m: 'LD A,(nn)', o: '3A nn nn', b: 3, c: '13', f: '------', d: 'Load A from memory', g: 'load' },
    { m: 'LD (BC),A', o: '02', b: 1, c: '7', f: '------', d: 'Load (BC) from A', g: 'load' },
    { m: 'LD (DE),A', o: '12', b: 1, c: '7', f: '------', d: 'Load (DE) from A', g: 'load' },
    { m: 'LD (nn),A', o: '32 nn nn', b: 3, c: '13', f: '------', d: 'Load memory from A', g: 'load' },
    { m: 'LD A,I', o: 'ED 57', b: 2, c: '9', f: 'SZ*P0-', d: 'Load A from I', g: 'load' },
    { m: 'LD A,R', o: 'ED 5F', b: 2, c: '9', f: 'SZ*P0-', d: 'Load A from R', g: 'load' },
    { m: 'LD I,A', o: 'ED 47', b: 2, c: '9', f: '------', d: 'Load I from A', g: 'load' },
    { m: 'LD R,A', o: 'ED 4F', b: 2, c: '9', f: '------', d: 'Load R from A', g: 'load' },
    // Undocumented LD with IXH/IXL/IYH/IYL
    { m: 'LD A,IXH', o: 'DD 7C', b: 2, c: '8', f: '------', d: 'Load A from IXH', g: 'load', u: true },
    { m: 'LD A,IXL', o: 'DD 7D', b: 2, c: '8', f: '------', d: 'Load A from IXL', g: 'load', u: true },
    { m: 'LD A,IYH', o: 'FD 7C', b: 2, c: '8', f: '------', d: 'Load A from IYH', g: 'load', u: true },
    { m: 'LD A,IYL', o: 'FD 7D', b: 2, c: '8', f: '------', d: 'Load A from IYL', g: 'load', u: true },
    { m: 'LD IXH,A', o: 'DD 67', b: 2, c: '8', f: '------', d: 'Load IXH from A', g: 'load', u: true },
    { m: 'LD IXL,A', o: 'DD 6F', b: 2, c: '8', f: '------', d: 'Load IXL from A', g: 'load', u: true },
    { m: 'LD IYH,A', o: 'FD 67', b: 2, c: '8', f: '------', d: 'Load IYH from A', g: 'load', u: true },
    { m: 'LD IYL,A', o: 'FD 6F', b: 2, c: '8', f: '------', d: 'Load IYL from A', g: 'load', u: true },
    { m: 'LD IXH,n', o: 'DD 26 nn', b: 3, c: '11', f: '------', d: 'Load IXH with immediate', g: 'load', u: true },
    { m: 'LD IXL,n', o: 'DD 2E nn', b: 3, c: '11', f: '------', d: 'Load IXL with immediate', g: 'load', u: true },
    { m: 'LD IYH,n', o: 'FD 26 nn', b: 3, c: '11', f: '------', d: 'Load IYH with immediate', g: 'load', u: true },
    { m: 'LD IYL,n', o: 'FD 2E nn', b: 3, c: '11', f: '------', d: 'Load IYL with immediate', g: 'load', u: true },
    // Load 16-bit
    { m: 'LD BC,nn', o: '01 nn nn', b: 3, c: '10', f: '------', d: 'Load BC with immediate', g: 'load' },
    { m: 'LD DE,nn', o: '11 nn nn', b: 3, c: '10', f: '------', d: 'Load DE with immediate', g: 'load' },
    { m: 'LD HL,nn', o: '21 nn nn', b: 3, c: '10', f: '------', d: 'Load HL with immediate', g: 'load' },
    { m: 'LD SP,nn', o: '31 nn nn', b: 3, c: '10', f: '------', d: 'Load SP with immediate', g: 'load' },
    { m: 'LD IX,nn', o: 'DD 21 nn nn', b: 4, c: '14', f: '------', d: 'Load IX with immediate', g: 'load' },
    { m: 'LD IY,nn', o: 'FD 21 nn nn', b: 4, c: '14', f: '------', d: 'Load IY with immediate', g: 'load' },
    { m: 'LD HL,(nn)', o: '2A nn nn', b: 3, c: '16', f: '------', d: 'Load HL from memory', g: 'load' },
    { m: 'LD BC,(nn)', o: 'ED 4B nn nn', b: 4, c: '20', f: '------', d: 'Load BC from memory', g: 'load' },
    { m: 'LD DE,(nn)', o: 'ED 5B nn nn', b: 4, c: '20', f: '------', d: 'Load DE from memory', g: 'load' },
    { m: 'LD SP,(nn)', o: 'ED 7B nn nn', b: 4, c: '20', f: '------', d: 'Load SP from memory', g: 'load' },
    { m: 'LD IX,(nn)', o: 'DD 2A nn nn', b: 4, c: '20', f: '------', d: 'Load IX from memory', g: 'load' },
    { m: 'LD IY,(nn)', o: 'FD 2A nn nn', b: 4, c: '20', f: '------', d: 'Load IY from memory', g: 'load' },
    { m: 'LD (nn),HL', o: '22 nn nn', b: 3, c: '16', f: '------', d: 'Load memory from HL', g: 'load' },
    { m: 'LD (nn),BC', o: 'ED 43 nn nn', b: 4, c: '20', f: '------', d: 'Load memory from BC', g: 'load' },
    { m: 'LD (nn),DE', o: 'ED 53 nn nn', b: 4, c: '20', f: '------', d: 'Load memory from DE', g: 'load' },
    { m: 'LD (nn),SP', o: 'ED 73 nn nn', b: 4, c: '20', f: '------', d: 'Load memory from SP', g: 'load' },
    { m: 'LD (nn),IX', o: 'DD 22 nn nn', b: 4, c: '20', f: '------', d: 'Load memory from IX', g: 'load' },
    { m: 'LD (nn),IY', o: 'FD 22 nn nn', b: 4, c: '20', f: '------', d: 'Load memory from IY', g: 'load' },
    { m: 'LD SP,HL', o: 'F9', b: 1, c: '6', f: '------', d: 'Load SP from HL', g: 'load' },
    { m: 'LD SP,IX', o: 'DD F9', b: 2, c: '10', f: '------', d: 'Load SP from IX', g: 'load' },
    { m: 'LD SP,IY', o: 'FD F9', b: 2, c: '10', f: '------', d: 'Load SP from IY', g: 'load' },
    { m: 'PUSH AF', o: 'F5', b: 1, c: '11', f: '------', d: 'Push AF to stack', g: 'load' },
    { m: 'PUSH BC', o: 'C5', b: 1, c: '11', f: '------', d: 'Push BC to stack', g: 'load' },
    { m: 'PUSH DE', o: 'D5', b: 1, c: '11', f: '------', d: 'Push DE to stack', g: 'load' },
    { m: 'PUSH HL', o: 'E5', b: 1, c: '11', f: '------', d: 'Push HL to stack', g: 'load' },
    { m: 'PUSH IX', o: 'DD E5', b: 2, c: '15', f: '------', d: 'Push IX to stack', g: 'load' },
    { m: 'PUSH IY', o: 'FD E5', b: 2, c: '15', f: '------', d: 'Push IY to stack', g: 'load' },
    { m: 'POP AF', o: 'F1', b: 1, c: '10', f: '------', d: 'Pop AF from stack', g: 'load' },
    { m: 'POP BC', o: 'C1', b: 1, c: '10', f: '------', d: 'Pop BC from stack', g: 'load' },
    { m: 'POP DE', o: 'D1', b: 1, c: '10', f: '------', d: 'Pop DE from stack', g: 'load' },
    { m: 'POP HL', o: 'E1', b: 1, c: '10', f: '------', d: 'Pop HL from stack', g: 'load' },
    { m: 'POP IX', o: 'DD E1', b: 2, c: '14', f: '------', d: 'Pop IX from stack', g: 'load' },
    { m: 'POP IY', o: 'FD E1', b: 2, c: '14', f: '------', d: 'Pop IY from stack', g: 'load' },
    // Exchange
    { m: 'EX DE,HL', o: 'EB', b: 1, c: '4', f: '------', d: 'Exchange DE and HL', g: 'load' },
    { m: 'EX AF,AF\'', o: '08', b: 1, c: '4', f: '------', d: 'Exchange AF and AF\'', g: 'load' },
    { m: 'EXX', o: 'D9', b: 1, c: '4', f: '------', d: 'Exchange BC,DE,HL with alternates', g: 'load' },
    { m: 'EX (SP),HL', o: 'E3', b: 1, c: '19', f: '------', d: 'Exchange (SP) and HL', g: 'load' },
    { m: 'EX (SP),IX', o: 'DD E3', b: 2, c: '23', f: '------', d: 'Exchange (SP) and IX', g: 'load' },
    { m: 'EX (SP),IY', o: 'FD E3', b: 2, c: '23', f: '------', d: 'Exchange (SP) and IY', g: 'load' },
    // Arithmetic 8-bit
    { m: 'ADD A,A', o: '87', b: 1, c: '4', f: 'SZ*V0C', d: 'Add A to A', g: 'arith' },
    { m: 'ADD A,B', o: '80', b: 1, c: '4', f: 'SZ*V0C', d: 'Add B to A', g: 'arith' },
    { m: 'ADD A,C', o: '81', b: 1, c: '4', f: 'SZ*V0C', d: 'Add C to A', g: 'arith' },
    { m: 'ADD A,D', o: '82', b: 1, c: '4', f: 'SZ*V0C', d: 'Add D to A', g: 'arith' },
    { m: 'ADD A,E', o: '83', b: 1, c: '4', f: 'SZ*V0C', d: 'Add E to A', g: 'arith' },
    { m: 'ADD A,H', o: '84', b: 1, c: '4', f: 'SZ*V0C', d: 'Add H to A', g: 'arith' },
    { m: 'ADD A,L', o: '85', b: 1, c: '4', f: 'SZ*V0C', d: 'Add L to A', g: 'arith' },
    { m: 'ADD A,n', o: 'C6 nn', b: 2, c: '7', f: 'SZ*V0C', d: 'Add immediate to A', g: 'arith' },
    { m: 'ADD A,(HL)', o: '86', b: 1, c: '7', f: 'SZ*V0C', d: 'Add (HL) to A', g: 'arith' },
    { m: 'ADD A,(IX+d)', o: 'DD 86 dd', b: 3, c: '19', f: 'SZ*V0C', d: 'Add (IX+d) to A', g: 'arith' },
    { m: 'ADD A,(IY+d)', o: 'FD 86 dd', b: 3, c: '19', f: 'SZ*V0C', d: 'Add (IY+d) to A', g: 'arith' },
    { m: 'ADD A,IXH', o: 'DD 84', b: 2, c: '8', f: 'SZ*V0C', d: 'Add IXH to A', g: 'arith', u: true },
    { m: 'ADD A,IXL', o: 'DD 85', b: 2, c: '8', f: 'SZ*V0C', d: 'Add IXL to A', g: 'arith', u: true },
    { m: 'ADD A,IYH', o: 'FD 84', b: 2, c: '8', f: 'SZ*V0C', d: 'Add IYH to A', g: 'arith', u: true },
    { m: 'ADD A,IYL', o: 'FD 85', b: 2, c: '8', f: 'SZ*V0C', d: 'Add IYL to A', g: 'arith', u: true },
    { m: 'ADC A,A', o: '8F', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry A to A', g: 'arith' },
    { m: 'ADC A,B', o: '88', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry B to A', g: 'arith' },
    { m: 'ADC A,C', o: '89', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry C to A', g: 'arith' },
    { m: 'ADC A,D', o: '8A', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry D to A', g: 'arith' },
    { m: 'ADC A,E', o: '8B', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry E to A', g: 'arith' },
    { m: 'ADC A,H', o: '8C', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry H to A', g: 'arith' },
    { m: 'ADC A,L', o: '8D', b: 1, c: '4', f: 'SZ*V0C', d: 'Add with carry L to A', g: 'arith' },
    { m: 'ADC A,n', o: 'CE nn', b: 2, c: '7', f: 'SZ*V0C', d: 'Add with carry immediate to A', g: 'arith' },
    { m: 'ADC A,(HL)', o: '8E', b: 1, c: '7', f: 'SZ*V0C', d: 'Add with carry (HL) to A', g: 'arith' },
    { m: 'ADC A,(IX+d)', o: 'DD 8E dd', b: 3, c: '19', f: 'SZ*V0C', d: 'Add with carry (IX+d) to A', g: 'arith' },
    { m: 'ADC A,(IY+d)', o: 'FD 8E dd', b: 3, c: '19', f: 'SZ*V0C', d: 'Add with carry (IY+d) to A', g: 'arith' },
    { m: 'SUB A', o: '97', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract A from A', g: 'arith' },
    { m: 'SUB B', o: '90', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract B from A', g: 'arith' },
    { m: 'SUB C', o: '91', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract C from A', g: 'arith' },
    { m: 'SUB D', o: '92', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract D from A', g: 'arith' },
    { m: 'SUB E', o: '93', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract E from A', g: 'arith' },
    { m: 'SUB H', o: '94', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract H from A', g: 'arith' },
    { m: 'SUB L', o: '95', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract L from A', g: 'arith' },
    { m: 'SUB n', o: 'D6 nn', b: 2, c: '7', f: 'SZ*V1C', d: 'Subtract immediate from A', g: 'arith' },
    { m: 'SUB (HL)', o: '96', b: 1, c: '7', f: 'SZ*V1C', d: 'Subtract (HL) from A', g: 'arith' },
    { m: 'SUB (IX+d)', o: 'DD 96 dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Subtract (IX+d) from A', g: 'arith' },
    { m: 'SUB (IY+d)', o: 'FD 96 dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Subtract (IY+d) from A', g: 'arith' },
    { m: 'SBC A,A', o: '9F', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry A from A', g: 'arith' },
    { m: 'SBC A,B', o: '98', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry B from A', g: 'arith' },
    { m: 'SBC A,C', o: '99', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry C from A', g: 'arith' },
    { m: 'SBC A,D', o: '9A', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry D from A', g: 'arith' },
    { m: 'SBC A,E', o: '9B', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry E from A', g: 'arith' },
    { m: 'SBC A,H', o: '9C', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry H from A', g: 'arith' },
    { m: 'SBC A,L', o: '9D', b: 1, c: '4', f: 'SZ*V1C', d: 'Subtract with carry L from A', g: 'arith' },
    { m: 'SBC A,n', o: 'DE nn', b: 2, c: '7', f: 'SZ*V1C', d: 'Subtract with carry immediate from A', g: 'arith' },
    { m: 'SBC A,(HL)', o: '9E', b: 1, c: '7', f: 'SZ*V1C', d: 'Subtract with carry (HL) from A', g: 'arith' },
    { m: 'SBC A,(IX+d)', o: 'DD 9E dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Subtract with carry (IX+d) from A', g: 'arith' },
    { m: 'SBC A,(IY+d)', o: 'FD 9E dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Subtract with carry (IY+d) from A', g: 'arith' },
    { m: 'CP A', o: 'BF', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare A with A', g: 'arith' },
    { m: 'CP B', o: 'B8', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare B with A', g: 'arith' },
    { m: 'CP C', o: 'B9', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare C with A', g: 'arith' },
    { m: 'CP D', o: 'BA', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare D with A', g: 'arith' },
    { m: 'CP E', o: 'BB', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare E with A', g: 'arith' },
    { m: 'CP H', o: 'BC', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare H with A', g: 'arith' },
    { m: 'CP L', o: 'BD', b: 1, c: '4', f: 'SZ*V1C', d: 'Compare L with A', g: 'arith' },
    { m: 'CP n', o: 'FE nn', b: 2, c: '7', f: 'SZ*V1C', d: 'Compare immediate with A', g: 'arith' },
    { m: 'CP (HL)', o: 'BE', b: 1, c: '7', f: 'SZ*V1C', d: 'Compare (HL) with A', g: 'arith' },
    { m: 'CP (IX+d)', o: 'DD BE dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Compare (IX+d) with A', g: 'arith' },
    { m: 'CP (IY+d)', o: 'FD BE dd', b: 3, c: '19', f: 'SZ*V1C', d: 'Compare (IY+d) with A', g: 'arith' },
    { m: 'INC A', o: '3C', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment A', g: 'arith' },
    { m: 'INC B', o: '04', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment B', g: 'arith' },
    { m: 'INC C', o: '0C', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment C', g: 'arith' },
    { m: 'INC D', o: '14', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment D', g: 'arith' },
    { m: 'INC E', o: '1C', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment E', g: 'arith' },
    { m: 'INC H', o: '24', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment H', g: 'arith' },
    { m: 'INC L', o: '2C', b: 1, c: '4', f: 'SZ*V0-', d: 'Increment L', g: 'arith' },
    { m: 'INC (HL)', o: '34', b: 1, c: '11', f: 'SZ*V0-', d: 'Increment (HL)', g: 'arith' },
    { m: 'INC (IX+d)', o: 'DD 34 dd', b: 3, c: '23', f: 'SZ*V0-', d: 'Increment (IX+d)', g: 'arith' },
    { m: 'INC (IY+d)', o: 'FD 34 dd', b: 3, c: '23', f: 'SZ*V0-', d: 'Increment (IY+d)', g: 'arith' },
    { m: 'INC IXH', o: 'DD 24', b: 2, c: '8', f: 'SZ*V0-', d: 'Increment IXH', g: 'arith', u: true },
    { m: 'INC IXL', o: 'DD 2C', b: 2, c: '8', f: 'SZ*V0-', d: 'Increment IXL', g: 'arith', u: true },
    { m: 'INC IYH', o: 'FD 24', b: 2, c: '8', f: 'SZ*V0-', d: 'Increment IYH', g: 'arith', u: true },
    { m: 'INC IYL', o: 'FD 2C', b: 2, c: '8', f: 'SZ*V0-', d: 'Increment IYL', g: 'arith', u: true },
    { m: 'DEC A', o: '3D', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement A', g: 'arith' },
    { m: 'DEC B', o: '05', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement B', g: 'arith' },
    { m: 'DEC C', o: '0D', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement C', g: 'arith' },
    { m: 'DEC D', o: '15', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement D', g: 'arith' },
    { m: 'DEC E', o: '1D', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement E', g: 'arith' },
    { m: 'DEC H', o: '25', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement H', g: 'arith' },
    { m: 'DEC L', o: '2D', b: 1, c: '4', f: 'SZ*V1-', d: 'Decrement L', g: 'arith' },
    { m: 'DEC (HL)', o: '35', b: 1, c: '11', f: 'SZ*V1-', d: 'Decrement (HL)', g: 'arith' },
    { m: 'DEC (IX+d)', o: 'DD 35 dd', b: 3, c: '23', f: 'SZ*V1-', d: 'Decrement (IX+d)', g: 'arith' },
    { m: 'DEC (IY+d)', o: 'FD 35 dd', b: 3, c: '23', f: 'SZ*V1-', d: 'Decrement (IY+d)', g: 'arith' },
    { m: 'DEC IXH', o: 'DD 25', b: 2, c: '8', f: 'SZ*V1-', d: 'Decrement IXH', g: 'arith', u: true },
    { m: 'DEC IXL', o: 'DD 2D', b: 2, c: '8', f: 'SZ*V1-', d: 'Decrement IXL', g: 'arith', u: true },
    { m: 'DEC IYH', o: 'FD 25', b: 2, c: '8', f: 'SZ*V1-', d: 'Decrement IYH', g: 'arith', u: true },
    { m: 'DEC IYL', o: 'FD 2D', b: 2, c: '8', f: 'SZ*V1-', d: 'Decrement IYL', g: 'arith', u: true },
    { m: 'DAA', o: '27', b: 1, c: '4', f: 'SZ*P-C', d: 'Decimal adjust A', g: 'arith' },
    { m: 'NEG', o: 'ED 44', b: 2, c: '8', f: 'SZ*V1C', d: 'Negate A (two\'s complement)', g: 'arith' },
    // Arithmetic 16-bit
    { m: 'ADD HL,BC', o: '09', b: 1, c: '11', f: '--*-0C', d: 'Add BC to HL', g: 'arith' },
    { m: 'ADD HL,DE', o: '19', b: 1, c: '11', f: '--*-0C', d: 'Add DE to HL', g: 'arith' },
    { m: 'ADD HL,HL', o: '29', b: 1, c: '11', f: '--*-0C', d: 'Add HL to HL', g: 'arith' },
    { m: 'ADD HL,SP', o: '39', b: 1, c: '11', f: '--*-0C', d: 'Add SP to HL', g: 'arith' },
    { m: 'ADC HL,BC', o: 'ED 4A', b: 2, c: '15', f: 'SZ*V0C', d: 'Add with carry BC to HL', g: 'arith' },
    { m: 'ADC HL,DE', o: 'ED 5A', b: 2, c: '15', f: 'SZ*V0C', d: 'Add with carry DE to HL', g: 'arith' },
    { m: 'ADC HL,HL', o: 'ED 6A', b: 2, c: '15', f: 'SZ*V0C', d: 'Add with carry HL to HL', g: 'arith' },
    { m: 'ADC HL,SP', o: 'ED 7A', b: 2, c: '15', f: 'SZ*V0C', d: 'Add with carry SP to HL', g: 'arith' },
    { m: 'SBC HL,BC', o: 'ED 42', b: 2, c: '15', f: 'SZ*V1C', d: 'Subtract with carry BC from HL', g: 'arith' },
    { m: 'SBC HL,DE', o: 'ED 52', b: 2, c: '15', f: 'SZ*V1C', d: 'Subtract with carry DE from HL', g: 'arith' },
    { m: 'SBC HL,HL', o: 'ED 62', b: 2, c: '15', f: 'SZ*V1C', d: 'Subtract with carry HL from HL', g: 'arith' },
    { m: 'SBC HL,SP', o: 'ED 72', b: 2, c: '15', f: 'SZ*V1C', d: 'Subtract with carry SP from HL', g: 'arith' },
    { m: 'ADD IX,BC', o: 'DD 09', b: 2, c: '15', f: '--*-0C', d: 'Add BC to IX', g: 'arith' },
    { m: 'ADD IX,DE', o: 'DD 19', b: 2, c: '15', f: '--*-0C', d: 'Add DE to IX', g: 'arith' },
    { m: 'ADD IX,IX', o: 'DD 29', b: 2, c: '15', f: '--*-0C', d: 'Add IX to IX', g: 'arith' },
    { m: 'ADD IX,SP', o: 'DD 39', b: 2, c: '15', f: '--*-0C', d: 'Add SP to IX', g: 'arith' },
    { m: 'ADD IY,BC', o: 'FD 09', b: 2, c: '15', f: '--*-0C', d: 'Add BC to IY', g: 'arith' },
    { m: 'ADD IY,DE', o: 'FD 19', b: 2, c: '15', f: '--*-0C', d: 'Add DE to IY', g: 'arith' },
    { m: 'ADD IY,IY', o: 'FD 29', b: 2, c: '15', f: '--*-0C', d: 'Add IY to IY', g: 'arith' },
    { m: 'ADD IY,SP', o: 'FD 39', b: 2, c: '15', f: '--*-0C', d: 'Add SP to IY', g: 'arith' },
    { m: 'INC BC', o: '03', b: 1, c: '6', f: '------', d: 'Increment BC', g: 'arith' },
    { m: 'INC DE', o: '13', b: 1, c: '6', f: '------', d: 'Increment DE', g: 'arith' },
    { m: 'INC HL', o: '23', b: 1, c: '6', f: '------', d: 'Increment HL', g: 'arith' },
    { m: 'INC SP', o: '33', b: 1, c: '6', f: '------', d: 'Increment SP', g: 'arith' },
    { m: 'INC IX', o: 'DD 23', b: 2, c: '10', f: '------', d: 'Increment IX', g: 'arith' },
    { m: 'INC IY', o: 'FD 23', b: 2, c: '10', f: '------', d: 'Increment IY', g: 'arith' },
    { m: 'DEC BC', o: '0B', b: 1, c: '6', f: '------', d: 'Decrement BC', g: 'arith' },
    { m: 'DEC DE', o: '1B', b: 1, c: '6', f: '------', d: 'Decrement DE', g: 'arith' },
    { m: 'DEC HL', o: '2B', b: 1, c: '6', f: '------', d: 'Decrement HL', g: 'arith' },
    { m: 'DEC SP', o: '3B', b: 1, c: '6', f: '------', d: 'Decrement SP', g: 'arith' },
    { m: 'DEC IX', o: 'DD 2B', b: 2, c: '10', f: '------', d: 'Decrement IX', g: 'arith' },
    { m: 'DEC IY', o: 'FD 2B', b: 2, c: '10', f: '------', d: 'Decrement IY', g: 'arith' },
    // Logic
    { m: 'AND A', o: 'A7', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND A with A', g: 'logic' },
    { m: 'AND B', o: 'A0', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND B with A', g: 'logic' },
    { m: 'AND C', o: 'A1', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND C with A', g: 'logic' },
    { m: 'AND D', o: 'A2', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND D with A', g: 'logic' },
    { m: 'AND E', o: 'A3', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND E with A', g: 'logic' },
    { m: 'AND H', o: 'A4', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND H with A', g: 'logic' },
    { m: 'AND L', o: 'A5', b: 1, c: '4', f: 'SZ*P10', d: 'Logical AND L with A', g: 'logic' },
    { m: 'AND n', o: 'E6 nn', b: 2, c: '7', f: 'SZ*P10', d: 'Logical AND immediate with A', g: 'logic' },
    { m: 'AND (HL)', o: 'A6', b: 1, c: '7', f: 'SZ*P10', d: 'Logical AND (HL) with A', g: 'logic' },
    { m: 'AND (IX+d)', o: 'DD A6 dd', b: 3, c: '19', f: 'SZ*P10', d: 'Logical AND (IX+d) with A', g: 'logic' },
    { m: 'AND (IY+d)', o: 'FD A6 dd', b: 3, c: '19', f: 'SZ*P10', d: 'Logical AND (IY+d) with A', g: 'logic' },
    { m: 'OR A', o: 'B7', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR A with A', g: 'logic' },
    { m: 'OR B', o: 'B0', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR B with A', g: 'logic' },
    { m: 'OR C', o: 'B1', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR C with A', g: 'logic' },
    { m: 'OR D', o: 'B2', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR D with A', g: 'logic' },
    { m: 'OR E', o: 'B3', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR E with A', g: 'logic' },
    { m: 'OR H', o: 'B4', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR H with A', g: 'logic' },
    { m: 'OR L', o: 'B5', b: 1, c: '4', f: 'SZ*P00', d: 'Logical OR L with A', g: 'logic' },
    { m: 'OR n', o: 'F6 nn', b: 2, c: '7', f: 'SZ*P00', d: 'Logical OR immediate with A', g: 'logic' },
    { m: 'OR (HL)', o: 'B6', b: 1, c: '7', f: 'SZ*P00', d: 'Logical OR (HL) with A', g: 'logic' },
    { m: 'OR (IX+d)', o: 'DD B6 dd', b: 3, c: '19', f: 'SZ*P00', d: 'Logical OR (IX+d) with A', g: 'logic' },
    { m: 'OR (IY+d)', o: 'FD B6 dd', b: 3, c: '19', f: 'SZ*P00', d: 'Logical OR (IY+d) with A', g: 'logic' },
    { m: 'XOR A', o: 'AF', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR A with A', g: 'logic' },
    { m: 'XOR B', o: 'A8', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR B with A', g: 'logic' },
    { m: 'XOR C', o: 'A9', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR C with A', g: 'logic' },
    { m: 'XOR D', o: 'AA', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR D with A', g: 'logic' },
    { m: 'XOR E', o: 'AB', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR E with A', g: 'logic' },
    { m: 'XOR H', o: 'AC', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR H with A', g: 'logic' },
    { m: 'XOR L', o: 'AD', b: 1, c: '4', f: 'SZ*P00', d: 'Logical XOR L with A', g: 'logic' },
    { m: 'XOR n', o: 'EE nn', b: 2, c: '7', f: 'SZ*P00', d: 'Logical XOR immediate with A', g: 'logic' },
    { m: 'XOR (HL)', o: 'AE', b: 1, c: '7', f: 'SZ*P00', d: 'Logical XOR (HL) with A', g: 'logic' },
    { m: 'XOR (IX+d)', o: 'DD AE dd', b: 3, c: '19', f: 'SZ*P00', d: 'Logical XOR (IX+d) with A', g: 'logic' },
    { m: 'XOR (IY+d)', o: 'FD AE dd', b: 3, c: '19', f: 'SZ*P00', d: 'Logical XOR (IY+d) with A', g: 'logic' },
    { m: 'CPL', o: '2F', b: 1, c: '4', f: '--1-1-', d: 'Complement A (one\'s complement)', g: 'logic' },
    { m: 'CCF', o: '3F', b: 1, c: '4', f: '--*-0C', d: 'Complement carry flag', g: 'logic' },
    { m: 'SCF', o: '37', b: 1, c: '4', f: '--0-01', d: 'Set carry flag', g: 'logic' },
    // Rotate & Shift
    { m: 'RLCA', o: '07', b: 1, c: '4', f: '--0-0C', d: 'Rotate A left circular', g: 'rotate' },
    { m: 'RLA', o: '17', b: 1, c: '4', f: '--0-0C', d: 'Rotate A left through carry', g: 'rotate' },
    { m: 'RRCA', o: '0F', b: 1, c: '4', f: '--0-0C', d: 'Rotate A right circular', g: 'rotate' },
    { m: 'RRA', o: '1F', b: 1, c: '4', f: '--0-0C', d: 'Rotate A right through carry', g: 'rotate' },
    { m: 'RLC A', o: 'CB 07', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate A left circular', g: 'rotate' },
    { m: 'RLC B', o: 'CB 00', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate B left circular', g: 'rotate' },
    { m: 'RLC C', o: 'CB 01', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate C left circular', g: 'rotate' },
    { m: 'RLC D', o: 'CB 02', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate D left circular', g: 'rotate' },
    { m: 'RLC E', o: 'CB 03', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate E left circular', g: 'rotate' },
    { m: 'RLC H', o: 'CB 04', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate H left circular', g: 'rotate' },
    { m: 'RLC L', o: 'CB 05', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate L left circular', g: 'rotate' },
    { m: 'RLC (HL)', o: 'CB 06', b: 2, c: '15', f: 'SZ*P0C', d: 'Rotate (HL) left circular', g: 'rotate' },
    { m: 'RLC (IX+d)', o: 'DD CB dd 06', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IX+d) left circular', g: 'rotate' },
    { m: 'RLC (IY+d)', o: 'FD CB dd 06', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IY+d) left circular', g: 'rotate' },
    { m: 'RL A', o: 'CB 17', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate A left through carry', g: 'rotate' },
    { m: 'RL B', o: 'CB 10', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate B left through carry', g: 'rotate' },
    { m: 'RL C', o: 'CB 11', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate C left through carry', g: 'rotate' },
    { m: 'RL D', o: 'CB 12', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate D left through carry', g: 'rotate' },
    { m: 'RL E', o: 'CB 13', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate E left through carry', g: 'rotate' },
    { m: 'RL H', o: 'CB 14', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate H left through carry', g: 'rotate' },
    { m: 'RL L', o: 'CB 15', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate L left through carry', g: 'rotate' },
    { m: 'RL (HL)', o: 'CB 16', b: 2, c: '15', f: 'SZ*P0C', d: 'Rotate (HL) left through carry', g: 'rotate' },
    { m: 'RL (IX+d)', o: 'DD CB dd 16', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IX+d) left through carry', g: 'rotate' },
    { m: 'RL (IY+d)', o: 'FD CB dd 16', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IY+d) left through carry', g: 'rotate' },
    { m: 'RRC A', o: 'CB 0F', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate A right circular', g: 'rotate' },
    { m: 'RRC B', o: 'CB 08', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate B right circular', g: 'rotate' },
    { m: 'RRC C', o: 'CB 09', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate C right circular', g: 'rotate' },
    { m: 'RRC D', o: 'CB 0A', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate D right circular', g: 'rotate' },
    { m: 'RRC E', o: 'CB 0B', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate E right circular', g: 'rotate' },
    { m: 'RRC H', o: 'CB 0C', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate H right circular', g: 'rotate' },
    { m: 'RRC L', o: 'CB 0D', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate L right circular', g: 'rotate' },
    { m: 'RRC (HL)', o: 'CB 0E', b: 2, c: '15', f: 'SZ*P0C', d: 'Rotate (HL) right circular', g: 'rotate' },
    { m: 'RRC (IX+d)', o: 'DD CB dd 0E', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IX+d) right circular', g: 'rotate' },
    { m: 'RRC (IY+d)', o: 'FD CB dd 0E', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IY+d) right circular', g: 'rotate' },
    { m: 'RR A', o: 'CB 1F', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate A right through carry', g: 'rotate' },
    { m: 'RR B', o: 'CB 18', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate B right through carry', g: 'rotate' },
    { m: 'RR C', o: 'CB 19', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate C right through carry', g: 'rotate' },
    { m: 'RR D', o: 'CB 1A', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate D right through carry', g: 'rotate' },
    { m: 'RR E', o: 'CB 1B', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate E right through carry', g: 'rotate' },
    { m: 'RR H', o: 'CB 1C', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate H right through carry', g: 'rotate' },
    { m: 'RR L', o: 'CB 1D', b: 2, c: '8', f: 'SZ*P0C', d: 'Rotate L right through carry', g: 'rotate' },
    { m: 'RR (HL)', o: 'CB 1E', b: 2, c: '15', f: 'SZ*P0C', d: 'Rotate (HL) right through carry', g: 'rotate' },
    { m: 'RR (IX+d)', o: 'DD CB dd 1E', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IX+d) right through carry', g: 'rotate' },
    { m: 'RR (IY+d)', o: 'FD CB dd 1E', b: 4, c: '23', f: 'SZ*P0C', d: 'Rotate (IY+d) right through carry', g: 'rotate' },
    { m: 'SLA A', o: 'CB 27', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift A left arithmetic', g: 'rotate' },
    { m: 'SLA B', o: 'CB 20', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift B left arithmetic', g: 'rotate' },
    { m: 'SLA C', o: 'CB 21', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift C left arithmetic', g: 'rotate' },
    { m: 'SLA D', o: 'CB 22', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift D left arithmetic', g: 'rotate' },
    { m: 'SLA E', o: 'CB 23', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift E left arithmetic', g: 'rotate' },
    { m: 'SLA H', o: 'CB 24', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift H left arithmetic', g: 'rotate' },
    { m: 'SLA L', o: 'CB 25', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift L left arithmetic', g: 'rotate' },
    { m: 'SLA (HL)', o: 'CB 26', b: 2, c: '15', f: 'SZ*P0C', d: 'Shift (HL) left arithmetic', g: 'rotate' },
    { m: 'SLA (IX+d)', o: 'DD CB dd 26', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IX+d) left arithmetic', g: 'rotate' },
    { m: 'SLA (IY+d)', o: 'FD CB dd 26', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IY+d) left arithmetic', g: 'rotate' },
    { m: 'SLL A', o: 'CB 37', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift A left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL B', o: 'CB 30', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift B left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL C', o: 'CB 31', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift C left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL D', o: 'CB 32', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift D left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL E', o: 'CB 33', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift E left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL H', o: 'CB 34', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift H left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL L', o: 'CB 35', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift L left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SLL (HL)', o: 'CB 36', b: 2, c: '15', f: 'SZ*P0C', d: 'Shift (HL) left logical (bit0=1)', g: 'rotate', u: true },
    { m: 'SRA A', o: 'CB 2F', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift A right arithmetic', g: 'rotate' },
    { m: 'SRA B', o: 'CB 28', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift B right arithmetic', g: 'rotate' },
    { m: 'SRA C', o: 'CB 29', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift C right arithmetic', g: 'rotate' },
    { m: 'SRA D', o: 'CB 2A', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift D right arithmetic', g: 'rotate' },
    { m: 'SRA E', o: 'CB 2B', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift E right arithmetic', g: 'rotate' },
    { m: 'SRA H', o: 'CB 2C', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift H right arithmetic', g: 'rotate' },
    { m: 'SRA L', o: 'CB 2D', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift L right arithmetic', g: 'rotate' },
    { m: 'SRA (HL)', o: 'CB 2E', b: 2, c: '15', f: 'SZ*P0C', d: 'Shift (HL) right arithmetic', g: 'rotate' },
    { m: 'SRA (IX+d)', o: 'DD CB dd 2E', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IX+d) right arithmetic', g: 'rotate' },
    { m: 'SRA (IY+d)', o: 'FD CB dd 2E', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IY+d) right arithmetic', g: 'rotate' },
    { m: 'SRL A', o: 'CB 3F', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift A right logical', g: 'rotate' },
    { m: 'SRL B', o: 'CB 38', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift B right logical', g: 'rotate' },
    { m: 'SRL C', o: 'CB 39', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift C right logical', g: 'rotate' },
    { m: 'SRL D', o: 'CB 3A', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift D right logical', g: 'rotate' },
    { m: 'SRL E', o: 'CB 3B', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift E right logical', g: 'rotate' },
    { m: 'SRL H', o: 'CB 3C', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift H right logical', g: 'rotate' },
    { m: 'SRL L', o: 'CB 3D', b: 2, c: '8', f: 'SZ*P0C', d: 'Shift L right logical', g: 'rotate' },
    { m: 'SRL (HL)', o: 'CB 3E', b: 2, c: '15', f: 'SZ*P0C', d: 'Shift (HL) right logical', g: 'rotate' },
    { m: 'SRL (IX+d)', o: 'DD CB dd 3E', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IX+d) right logical', g: 'rotate' },
    { m: 'SRL (IY+d)', o: 'FD CB dd 3E', b: 4, c: '23', f: 'SZ*P0C', d: 'Shift (IY+d) right logical', g: 'rotate' },
    { m: 'RLD', o: 'ED 6F', b: 2, c: '18', f: 'SZ*P0-', d: 'Rotate left digit', g: 'rotate' },
    { m: 'RRD', o: 'ED 67', b: 2, c: '18', f: 'SZ*P0-', d: 'Rotate right digit', g: 'rotate' },
    // Bit Operations (example opcodes for bit 0)
    { m: 'BIT 0,A', o: 'CB 47', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of A', g: 'bit' },
    { m: 'BIT 0,B', o: 'CB 40', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of B', g: 'bit' },
    { m: 'BIT 0,C', o: 'CB 41', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of C', g: 'bit' },
    { m: 'BIT 0,D', o: 'CB 42', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of D', g: 'bit' },
    { m: 'BIT 0,E', o: 'CB 43', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of E', g: 'bit' },
    { m: 'BIT 0,H', o: 'CB 44', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of H', g: 'bit' },
    { m: 'BIT 0,L', o: 'CB 45', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit 0 of L', g: 'bit' },
    { m: 'BIT 0,(HL)', o: 'CB 46', b: 2, c: '12', f: 'SZ?10-', d: 'Test bit 0 of (HL)', g: 'bit' },
    { m: 'BIT b,r', o: 'CB 40+8*b+r', b: 2, c: '8', f: 'SZ?10-', d: 'Test bit b of register (b=0-7)', g: 'bit' },
    { m: 'BIT b,(HL)', o: 'CB 46+8*b', b: 2, c: '12', f: 'SZ?10-', d: 'Test bit b of (HL) (b=0-7)', g: 'bit' },
    { m: 'BIT b,(IX+d)', o: 'DD CB dd 46+8*b', b: 4, c: '20', f: 'SZ?10-', d: 'Test bit b of (IX+d)', g: 'bit' },
    { m: 'BIT b,(IY+d)', o: 'FD CB dd 46+8*b', b: 4, c: '20', f: 'SZ?10-', d: 'Test bit b of (IY+d)', g: 'bit' },
    { m: 'SET 0,A', o: 'CB C7', b: 2, c: '8', f: '------', d: 'Set bit 0 of A', g: 'bit' },
    { m: 'SET 0,B', o: 'CB C0', b: 2, c: '8', f: '------', d: 'Set bit 0 of B', g: 'bit' },
    { m: 'SET 0,C', o: 'CB C1', b: 2, c: '8', f: '------', d: 'Set bit 0 of C', g: 'bit' },
    { m: 'SET 0,D', o: 'CB C2', b: 2, c: '8', f: '------', d: 'Set bit 0 of D', g: 'bit' },
    { m: 'SET 0,E', o: 'CB C3', b: 2, c: '8', f: '------', d: 'Set bit 0 of E', g: 'bit' },
    { m: 'SET 0,H', o: 'CB C4', b: 2, c: '8', f: '------', d: 'Set bit 0 of H', g: 'bit' },
    { m: 'SET 0,L', o: 'CB C5', b: 2, c: '8', f: '------', d: 'Set bit 0 of L', g: 'bit' },
    { m: 'SET 0,(HL)', o: 'CB C6', b: 2, c: '15', f: '------', d: 'Set bit 0 of (HL)', g: 'bit' },
    { m: 'SET b,r', o: 'CB C0+8*b+r', b: 2, c: '8', f: '------', d: 'Set bit b of register (b=0-7)', g: 'bit' },
    { m: 'SET b,(HL)', o: 'CB C6+8*b', b: 2, c: '15', f: '------', d: 'Set bit b of (HL) (b=0-7)', g: 'bit' },
    { m: 'SET b,(IX+d)', o: 'DD CB dd C6+8*b', b: 4, c: '23', f: '------', d: 'Set bit b of (IX+d)', g: 'bit' },
    { m: 'SET b,(IY+d)', o: 'FD CB dd C6+8*b', b: 4, c: '23', f: '------', d: 'Set bit b of (IY+d)', g: 'bit' },
    { m: 'RES 0,A', o: 'CB 87', b: 2, c: '8', f: '------', d: 'Reset bit 0 of A', g: 'bit' },
    { m: 'RES 0,B', o: 'CB 80', b: 2, c: '8', f: '------', d: 'Reset bit 0 of B', g: 'bit' },
    { m: 'RES 0,C', o: 'CB 81', b: 2, c: '8', f: '------', d: 'Reset bit 0 of C', g: 'bit' },
    { m: 'RES 0,D', o: 'CB 82', b: 2, c: '8', f: '------', d: 'Reset bit 0 of D', g: 'bit' },
    { m: 'RES 0,E', o: 'CB 83', b: 2, c: '8', f: '------', d: 'Reset bit 0 of E', g: 'bit' },
    { m: 'RES 0,H', o: 'CB 84', b: 2, c: '8', f: '------', d: 'Reset bit 0 of H', g: 'bit' },
    { m: 'RES 0,L', o: 'CB 85', b: 2, c: '8', f: '------', d: 'Reset bit 0 of L', g: 'bit' },
    { m: 'RES 0,(HL)', o: 'CB 86', b: 2, c: '15', f: '------', d: 'Reset bit 0 of (HL)', g: 'bit' },
    { m: 'RES b,r', o: 'CB 80+8*b+r', b: 2, c: '8', f: '------', d: 'Reset bit b of register (b=0-7)', g: 'bit' },
    { m: 'RES b,(HL)', o: 'CB 86+8*b', b: 2, c: '15', f: '------', d: 'Reset bit b of (HL) (b=0-7)', g: 'bit' },
    { m: 'RES b,(IX+d)', o: 'DD CB dd 86+8*b', b: 4, c: '23', f: '------', d: 'Reset bit b of (IX+d)', g: 'bit' },
    { m: 'RES b,(IY+d)', o: 'FD CB dd 86+8*b', b: 4, c: '23', f: '------', d: 'Reset bit b of (IY+d)', g: 'bit' },
    // Jump
    { m: 'JP nn', o: 'C3 nn nn', b: 3, c: '10', f: '------', d: 'Jump to address', g: 'jump' },
    { m: 'JP NZ,nn', o: 'C2 nn nn', b: 3, c: '10', f: '------', d: 'Jump if not zero', g: 'jump' },
    { m: 'JP Z,nn', o: 'CA nn nn', b: 3, c: '10', f: '------', d: 'Jump if zero', g: 'jump' },
    { m: 'JP NC,nn', o: 'D2 nn nn', b: 3, c: '10', f: '------', d: 'Jump if no carry', g: 'jump' },
    { m: 'JP C,nn', o: 'DA nn nn', b: 3, c: '10', f: '------', d: 'Jump if carry', g: 'jump' },
    { m: 'JP PO,nn', o: 'E2 nn nn', b: 3, c: '10', f: '------', d: 'Jump if parity odd', g: 'jump' },
    { m: 'JP PE,nn', o: 'EA nn nn', b: 3, c: '10', f: '------', d: 'Jump if parity even', g: 'jump' },
    { m: 'JP P,nn', o: 'F2 nn nn', b: 3, c: '10', f: '------', d: 'Jump if positive', g: 'jump' },
    { m: 'JP M,nn', o: 'FA nn nn', b: 3, c: '10', f: '------', d: 'Jump if minus', g: 'jump' },
    { m: 'JR e', o: '18 ee', b: 2, c: '12', f: '------', d: 'Relative jump', g: 'jump' },
    { m: 'JR C,e', o: '38 ee', b: 2, c: '12/7', f: '------', d: 'Relative jump if carry', g: 'jump' },
    { m: 'JR NC,e', o: '30 ee', b: 2, c: '12/7', f: '------', d: 'Relative jump if no carry', g: 'jump' },
    { m: 'JR Z,e', o: '28 ee', b: 2, c: '12/7', f: '------', d: 'Relative jump if zero', g: 'jump' },
    { m: 'JR NZ,e', o: '20 ee', b: 2, c: '12/7', f: '------', d: 'Relative jump if not zero', g: 'jump' },
    { m: 'JP (HL)', o: 'E9', b: 1, c: '4', f: '------', d: 'Jump to address in HL', g: 'jump' },
    { m: 'JP (IX)', o: 'DD E9', b: 2, c: '8', f: '------', d: 'Jump to address in IX', g: 'jump' },
    { m: 'JP (IY)', o: 'FD E9', b: 2, c: '8', f: '------', d: 'Jump to address in IY', g: 'jump' },
    { m: 'DJNZ e', o: '10 ee', b: 2, c: '13/8', f: '------', d: 'Decrement B and jump if not zero', g: 'jump' },
    // Call & Return
    { m: 'CALL nn', o: 'CD nn nn', b: 3, c: '17', f: '------', d: 'Call subroutine', g: 'jump' },
    { m: 'CALL NZ,nn', o: 'C4 nn nn', b: 3, c: '17/10', f: '------', d: 'Call if not zero', g: 'jump' },
    { m: 'CALL Z,nn', o: 'CC nn nn', b: 3, c: '17/10', f: '------', d: 'Call if zero', g: 'jump' },
    { m: 'CALL NC,nn', o: 'D4 nn nn', b: 3, c: '17/10', f: '------', d: 'Call if no carry', g: 'jump' },
    { m: 'CALL C,nn', o: 'DC nn nn', b: 3, c: '17/10', f: '------', d: 'Call if carry', g: 'jump' },
    { m: 'CALL PO,nn', o: 'E4 nn nn', b: 3, c: '17/10', f: '------', d: 'Call if parity odd', g: 'jump' },
    { m: 'CALL PE,nn', o: 'EC nn nn', b: 3, c: '17/10', f: '------', d: 'Call if parity even', g: 'jump' },
    { m: 'CALL P,nn', o: 'F4 nn nn', b: 3, c: '17/10', f: '------', d: 'Call if positive', g: 'jump' },
    { m: 'CALL M,nn', o: 'FC nn nn', b: 3, c: '17/10', f: '------', d: 'Call if minus', g: 'jump' },
    { m: 'RET', o: 'C9', b: 1, c: '10', f: '------', d: 'Return from subroutine', g: 'jump' },
    { m: 'RET NZ', o: 'C0', b: 1, c: '11/5', f: '------', d: 'Return if not zero', g: 'jump' },
    { m: 'RET Z', o: 'C8', b: 1, c: '11/5', f: '------', d: 'Return if zero', g: 'jump' },
    { m: 'RET NC', o: 'D0', b: 1, c: '11/5', f: '------', d: 'Return if no carry', g: 'jump' },
    { m: 'RET C', o: 'D8', b: 1, c: '11/5', f: '------', d: 'Return if carry', g: 'jump' },
    { m: 'RET PO', o: 'E0', b: 1, c: '11/5', f: '------', d: 'Return if parity odd', g: 'jump' },
    { m: 'RET PE', o: 'E8', b: 1, c: '11/5', f: '------', d: 'Return if parity even', g: 'jump' },
    { m: 'RET P', o: 'F0', b: 1, c: '11/5', f: '------', d: 'Return if positive', g: 'jump' },
    { m: 'RET M', o: 'F8', b: 1, c: '11/5', f: '------', d: 'Return if minus', g: 'jump' },
    { m: 'RETI', o: 'ED 4D', b: 2, c: '14', f: '------', d: 'Return from interrupt', g: 'jump' },
    { m: 'RETN', o: 'ED 45', b: 2, c: '14', f: '------', d: 'Return from NMI', g: 'jump' },
    { m: 'RST 00H', o: 'C7', b: 1, c: '11', f: '------', d: 'Restart at 0000H', g: 'jump' },
    { m: 'RST 08H', o: 'CF', b: 1, c: '11', f: '------', d: 'Restart at 0008H', g: 'jump' },
    { m: 'RST 10H', o: 'D7', b: 1, c: '11', f: '------', d: 'Restart at 0010H', g: 'jump' },
    { m: 'RST 18H', o: 'DF', b: 1, c: '11', f: '------', d: 'Restart at 0018H', g: 'jump' },
    { m: 'RST 20H', o: 'E7', b: 1, c: '11', f: '------', d: 'Restart at 0020H', g: 'jump' },
    { m: 'RST 28H', o: 'EF', b: 1, c: '11', f: '------', d: 'Restart at 0028H', g: 'jump' },
    { m: 'RST 30H', o: 'F7', b: 1, c: '11', f: '------', d: 'Restart at 0030H', g: 'jump' },
    { m: 'RST 38H', o: 'FF', b: 1, c: '11', f: '------', d: 'Restart at 0038H', g: 'jump' },
    // I/O
    { m: 'IN A,(n)', o: 'DB nn', b: 2, c: '11', f: '------', d: 'Input from port n', g: 'io' },
    { m: 'IN A,(C)', o: 'ED 78', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to A', g: 'io' },
    { m: 'IN B,(C)', o: 'ED 40', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to B', g: 'io' },
    { m: 'IN C,(C)', o: 'ED 48', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to C', g: 'io' },
    { m: 'IN D,(C)', o: 'ED 50', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to D', g: 'io' },
    { m: 'IN E,(C)', o: 'ED 58', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to E', g: 'io' },
    { m: 'IN H,(C)', o: 'ED 60', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to H', g: 'io' },
    { m: 'IN L,(C)', o: 'ED 68', b: 2, c: '12', f: 'SZ*P0-', d: 'Input from port C to L', g: 'io' },
    { m: 'IN F,(C)', o: 'ED 70', b: 2, c: '12', f: 'SZ*P0-', d: 'Input port C, set flags only', g: 'io', u: true },
    { m: 'INI', o: 'ED A2', b: 2, c: '16', f: '?Z???-', d: 'Input and increment', g: 'io' },
    { m: 'INIR', o: 'ED B2', b: 2, c: '21/16', f: '?1???-', d: 'Input, increment and repeat', g: 'io' },
    { m: 'IND', o: 'ED AA', b: 2, c: '16', f: '?Z???-', d: 'Input and decrement', g: 'io' },
    { m: 'INDR', o: 'ED BA', b: 2, c: '21/16', f: '?1???-', d: 'Input, decrement and repeat', g: 'io' },
    { m: 'OUT (n),A', o: 'D3 nn', b: 2, c: '11', f: '------', d: 'Output A to port n', g: 'io' },
    { m: 'OUT (C),A', o: 'ED 79', b: 2, c: '12', f: '------', d: 'Output A to port C', g: 'io' },
    { m: 'OUT (C),B', o: 'ED 41', b: 2, c: '12', f: '------', d: 'Output B to port C', g: 'io' },
    { m: 'OUT (C),C', o: 'ED 49', b: 2, c: '12', f: '------', d: 'Output C to port C', g: 'io' },
    { m: 'OUT (C),D', o: 'ED 51', b: 2, c: '12', f: '------', d: 'Output D to port C', g: 'io' },
    { m: 'OUT (C),E', o: 'ED 59', b: 2, c: '12', f: '------', d: 'Output E to port C', g: 'io' },
    { m: 'OUT (C),H', o: 'ED 61', b: 2, c: '12', f: '------', d: 'Output H to port C', g: 'io' },
    { m: 'OUT (C),L', o: 'ED 69', b: 2, c: '12', f: '------', d: 'Output L to port C', g: 'io' },
    { m: 'OUT (C),0', o: 'ED 71', b: 2, c: '12', f: '------', d: 'Output 0 to port C', g: 'io', u: true },
    { m: 'OUTI', o: 'ED A3', b: 2, c: '16', f: '?Z???-', d: 'Output and increment', g: 'io' },
    { m: 'OTIR', o: 'ED B3', b: 2, c: '21/16', f: '?1???-', d: 'Output, increment and repeat', g: 'io' },
    { m: 'OUTD', o: 'ED AB', b: 2, c: '16', f: '?Z???-', d: 'Output and decrement', g: 'io' },
    { m: 'OTDR', o: 'ED BB', b: 2, c: '21/16', f: '?1???-', d: 'Output, decrement and repeat', g: 'io' },
    // Block Transfer
    { m: 'LDI', o: 'ED A0', b: 2, c: '16', f: '--0*0-', d: 'Load and increment', g: 'block' },
    { m: 'LDIR', o: 'ED B0', b: 2, c: '21/16', f: '--000-', d: 'Load, increment and repeat', g: 'block' },
    { m: 'LDD', o: 'ED A8', b: 2, c: '16', f: '--0*0-', d: 'Load and decrement', g: 'block' },
    { m: 'LDDR', o: 'ED B8', b: 2, c: '21/16', f: '--000-', d: 'Load, decrement and repeat', g: 'block' },
    { m: 'CPI', o: 'ED A1', b: 2, c: '16', f: 'SZ*?1-', d: 'Compare and increment', g: 'block' },
    { m: 'CPIR', o: 'ED B1', b: 2, c: '21/16', f: 'SZ*?1-', d: 'Compare, increment and repeat', g: 'block' },
    { m: 'CPD', o: 'ED A9', b: 2, c: '16', f: 'SZ*?1-', d: 'Compare and decrement', g: 'block' },
    { m: 'CPDR', o: 'ED B9', b: 2, c: '21/16', f: 'SZ*?1-', d: 'Compare, decrement and repeat', g: 'block' },
    // Misc
    { m: 'NOP', o: '00', b: 1, c: '4', f: '------', d: 'No operation', g: 'misc' },
    { m: 'HALT', o: '76', b: 1, c: '4', f: '------', d: 'Halt CPU until interrupt', g: 'misc' },
    { m: 'DI', o: 'F3', b: 1, c: '4', f: '------', d: 'Disable interrupts', g: 'misc' },
    { m: 'EI', o: 'FB', b: 1, c: '4', f: '------', d: 'Enable interrupts', g: 'misc' },
    { m: 'IM 0', o: 'ED 46', b: 2, c: '8', f: '------', d: 'Set interrupt mode 0', g: 'misc' },
    { m: 'IM 1', o: 'ED 56', b: 2, c: '8', f: '------', d: 'Set interrupt mode 1', g: 'misc' },
    { m: 'IM 2', o: 'ED 5E', b: 2, c: '8', f: '------', d: 'Set interrupt mode 2', g: 'misc' },
];
